repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
    - id: terraform-fmt
      args: ["-recursive"]
    - id: tflint
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.48.0
  hooks:
    - id: terraform_docs
    - id: terraform_tfsec
    - id: checkov
