---
formatter: markdown table
header-from: ./docs/header.md
sections:
  show:
    - data-sources
    - header
    - footer
    - inputs
    - modules
    - outputs
    - providers
    - requirements
    - resources
sort:
  enabled: true
  by: required
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: false
  html: true
  indent: 4
  lockfile: true
  required: true
  sensitive: true
  type: true
